language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - MIDGARD_EXT_VERSION=ratatoskr
  - MIDGARD_EXT_VERSION=master

before_script:
  - composer self-update
  - ./test/travis_midgard2.sh
  - composer install

script: sudo `which phpunit --debug`