'name' => 'midcom.extras.importer',
'purecode' => true,
'version' => '1',
'state' => 'stable',
'package.xml' => array
(
    'summary' => 'Importers',
    'description' => 'Various importers for other systems',
    'maintainers' => array
    (
        'flack' => array
        (
            'name' => 'Andreas Flack',
            'email' => 'flack@contentcontrol-berlin.de',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
