'name' => 'midcom.helper.datamanager2',
'icon' => 'midcom.helper.datamanager2/datamanager.png',
'version' => '9.2.0+git',
'state' => 'stable',
'purecode' => true,
'package.xml' => array
(
    'summary' => 'Addons for Datamanager 2',
    'description' => 'midcom.extras.datamanager2 provides some additional widgets and types to DM2',
    'state' => 'stable',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
        'torben' => array
        (
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
            'active' => 'no',
        ),
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'developer',
        ),
        'w_i' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@gmail.com',
            'role' => 'lead',
            'active' => 'no',
        ),
        'solt' => array
        (
            'name' => 'Marcin Sołtysiak',
            'email' => 'olga@olga.pl',
            'role' => 'developer',
        ),
        'jbergius' => array
        (
            'name' => 'Joonas Bergius',
            'email' => 'joonas.bergius@gmail.com',
            'role' => 'developer',
        ),
    ),
    'dependencies' => array
    (
        'net.nemein.tag' => array(),
        'midcom' => array(),
        'midcom.helper.reflector' => array
        (
            'min' => '1.0.1',
        ),
    ),
),
